language: python
python:
    - "3.5"
    - "3.6"

before_install:
    - "pip install -r REQUIREMENTS.txt"
    - "pip install coveralls"
    - "pip install coverage"

install: 
    - "pip install ."

script: 
    - "nosetests --with-coverage -v"
after_success:
    - coveralls
